//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : IKeyboardInput.cs
//  @ Date : 14/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using SFML.Graphics;
using SFML.System;
using SFML.Window;


public interface IKeyboardInput 
{
	void ProcessKeyboardPressed(object sender, KeyEventArgs e);
	void ProcessKeyboardReleased(object sender, KeyEventArgs e);
}
