//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Renderer.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

/// <summary>
/// Define um componente capaz de desenhar um frame de animação ou um Drawable em determinado RenderTarget
/// </summary>
public class Renderer : SFMLFramework.Component, IRender
{
    public SpriteSheet SpriteSheet { get; set; }

    public Player Player
    {
        get
        {
            throw new System.NotImplementedException();
        }

        set
        {
        }
    }

    /// <summary>
    /// Recebe uma instância da SpriteSheet que o componente deve renderizar
    /// </summary>
    public Renderer(SpriteSheet spriteSheet)
    {
        SpriteSheet = spriteSheet;
    }

    /// <summary>
    /// Renderiza o Sprite da SpriteSheet na janela informada
    /// </summary>
    public void Render(ref RenderTarget window)
    {
        window.Draw(this.SpriteSheet.Sprite);
    }

    public override void Update(float deltaTime)
    {
        SpriteSheet.UpdateAnimation(deltaTime);

    }
}