//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Renderer.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

public class Renderer : IRender
{
    protected SpriteSheet spriteSheet;

    public Renderer(SpriteSheet spriteSheet)
    {
        throw new System.NotImplementedException();
    }

    public SFML.Graphics.Drawable Renderable
    {
        get
        {
            throw new System.NotImplementedException();
        }

        set
        {
        }
    }

    public void Render(RenderTarget window)
    {
        window.Draw(this.spriteSheet.Sprite);
    }
}