//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : KeyboardInput.cs
//  @ Date : 14/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//aaa

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using SFML.Graphics;
using SFML.System;
using SFML.Window;

public delegate void OnKeyPressed(Keyboard.Key key);
public delegate void OnKeyReleased(Keyboard.Key key);

public class KeyboardInput : Component, IKeyboardInput
{
    public OnKeyPressed OnKeyPressed;
    public OnKeyReleased OnKeyReleased;

    public KeyboardInput(ref RenderWindow window) : base()
    {
        OnKeyPressed += (k) => { };
        OnKeyReleased += (k) => { };
    }


    public override void Update(float deltaTime)
    {
    }

    public void ProcessKeyboardPressed(object sender, KeyEventArgs e)
    {
        OnKeyPressed(e.Code);
    }

    public void ProcessKeyboardReleased(object sender, KeyEventArgs e)
    {
        OnKeyReleased(e.Code);
    }
}
