//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Collider.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

public class Collider : Component, ICollision
{
    protected Shape collider;

    public void CheckCollision(ICollision actor)
    {
        if(this.enabled)
            Console.WriteLine("CheckCollision");
    }

    public Shape GetShape()
    {
        return null;
    }

    public void SolveCollision()
    {
        if(this.enabled)
            Console.WriteLine("SolveCollision");
    }

    public override void Update(float deltaTime)
    {
        if(this.enabled)
            Console.WriteLine("Updating component");
    }    
}
