//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Game.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

public class Game : IUpdate
{
    public Vector2u windowSize;
    public string windowTitle;
    public Clock clock;
    protected RenderWindow window;
    public List<Actor> actors;

    public Game(string title)
    {
        this.windowTitle = title;
        this.actors = new List<Actor>();
        this.windowSize = new Vector2u(800, 600);
        this.clock = new Clock();        
    }

    public void Start()
    {
        this.window = new RenderWindow(new VideoMode(this.windowSize.X, this.windowSize.Y), windowTitle);

        Run();
    }

    protected void Run()
    {
        while(this.window.IsOpen)
        {
            window.DispatchEvents();
            Update(this.clock.ElapsedTime.AsSeconds());
            Render();
            this.clock.Restart();
        }
    }

    public void Update(float deltaTime)
    {
        this.actors.ForEach(a => a.Update(deltaTime));
    }

    protected void Render()
    {
        window.Clear();
        window.Display();
    }

    protected void Finish()
    {
    }
}
