//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Game.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;
using System.Threading;

public class Game : IUpdate
{
    public Vector2u windowSize;
    public string windowTitle;
    public Clock clock;
    protected RenderWindow window;
    public List<Actor> actors;
    private KeyboardInput keyboard;

    public Game(string title)
    {
        this.windowTitle = title;
        this.actors = new List<Actor>();
        this.windowSize = new Vector2u(800, 600);
        this.clock = new Clock();
        this.keyboard = new KeyboardInput(ref this.window);
    }

    public void Start()
    {
        this.window = new RenderWindow(new VideoMode(this.windowSize.X, this.windowSize.Y), windowTitle);
        this.window.SetFramerateLimit(60);
        this.window.KeyPressed += this.keyboard.ProcessKeyboardPressed;
        this.window.KeyReleased += this.keyboard.ProcessKeyboardReleased;

        var player = new Player();
        this.actors.Add(player);               
        
        this.keyboard.OnKeyPressed += player.keyboardController.OnKeyPressed;
        this.keyboard.OnKeyReleased += player.keyboardController.OnKeyReleased;                

        Run();
    }

    protected void Run()
    {
        while (this.window.IsOpen)
        {
            var timer = this.clock.Restart();

            window.DispatchEvents();
            Update(timer.AsSeconds());
            Render();
        }
    }

    public void Update(float deltaTime)
    {
        Console.WriteLine(deltaTime);
        this.actors.ForEach(a => a.Update(deltaTime));
    }

    protected void Render()
    {
        this.window.Clear();

        foreach (var a in actors)
        {
            a.GetComponent<Renderer>().Render(this.window);
        }

        this.window.Display();
    }

    protected void Finish()
    {
    }
}
