//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : IMove.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

public interface IMove
{
    void SetDirectionMove(Mover.Direction direction, bool value);
    Vector2f Position { get; set; }
    Mover.Direction direction { get; set; }
    Mover.OnDirectionChange OnChangeDirection { get; set; }
}
