//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Mover.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

public class Mover : Component, IMove
{
    public Vector2f Speed;
    protected Vector2f position;
    public Vector2f Position { get { return position; } }

    public Mover()
    {
        this.enabled = true;
    }

    public Mover(Vector2f position, Vector2f speed) : base()
    {
        this.enabled = true;
        this.position = position;
        this.Speed = speed;
    }


    public void Move(Vector2f direction)
    {
        if (this.enabled)
        {
            direction.X *= this.Speed.X;
            direction.Y *= this.Speed.Y;
            position += direction;
        }
    }

    public override void Update(float deltaTime)
    {
        if (this.enabled)
        { }
    }
}
