//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Renderer.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;

public class Renderer : Component, IRender
{
    public SpriteSheet spriteSheet;

    public Renderer() : base()
    {

    }

    public void Render(RenderTarget window)
    {
        window.Draw(this.spriteSheet.Sprite);
    }

    public override void Update(float deltaTime)
    {
        if (this.enabled)
        {
            this.spriteSheet.UpdateAnimation(deltaTime);
        }
    }
}
