//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Game.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SFML.System;
using System.Threading;
using SFMLFramework;

public class Game 
{
    public Vector2u windowSize;
    public string windowTitle;
    public Clock clock;
    protected RenderWindow window;
    private KeyboardInput keyboard;
    private Player player;

    public Game(string title)
    {
        this.windowTitle = title;
        this.windowSize = new Vector2u(800, 600);
        this.clock = new Clock();
        this.keyboard = new KeyboardInput(ref this.window);
        this.player = new Player();
    }

    public void Start()
    {
        this.window = new RenderWindow(new VideoMode(this.windowSize.X, this.windowSize.Y), windowTitle);
        this.window.SetFramerateLimit(60);
        this.window.KeyPressed += this.keyboard.ProcessKeyboardPressed;
        this.window.KeyReleased += this.keyboard.ProcessKeyboardReleased;
        this.player.SetKeyboardInput(ref this.keyboard);
        /*
        this.floor = new Entity("resources/floor.png", ECollisionType.None);
        this.floor.SetPosition(new Vector2f(0, 450));

        this.brick_1 = new Entity("resources/brick.png", ECollisionType.Inelastic);
        this.brick_1.SetPosition(new Vector2f(50, 280));

        this.brick_2 = new Entity("resources/brick2.png", ECollisionType.PartialInelastic);
        this.brick_2.SetPosition(new Vector2f(350, 300));

        this.brick_3 = new Entity("resources/brick3.png", ECollisionType.Elastic);
        this.brick_3.SetPosition(new Vector2f(480, 300));
        */
       
        Run();
    }

    public void Update(float deltaTime)
    {
        this.player.Update(deltaTime);

        /*
        CollisionDispatcher.CollisionCheck(this.player, this.floor);
        CollisionDispatcher.CollisionCheck(this.player, this.brick_1);
        CollisionDispatcher.CollisionCheck(this.player, this.brick_2);
        CollisionDispatcher.CollisionCheck(this.player, this.brick_3);

        CollisionDispatcher.CollisionCheck(this.brick_2, this.floor);
        CollisionDispatcher.CollisionCheck(this.brick_2, this.brick_1);
        CollisionDispatcher.CollisionCheck(this.brick_2, this.brick_3);

        CollisionDispatcher.CollisionCheck(this.brick_3, this.floor);
        CollisionDispatcher.CollisionCheck(this.brick_3, this.brick_1);
        CollisionDispatcher.CollisionCheck(this.brick_3, this.brick_2);
        */
    }

    protected void Run()
    {
        while (this.window.IsOpen)
        {
            var timer = this.clock.Restart();

            window.DispatchEvents();
            Update(timer.AsSeconds());
            Render();
        }
    }

    protected void Render()
    {
        this.window.Clear(Color.White);

        this.player.Renderer.Render(ref this.window);

        this.window.Display();
    }
}
