//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : SFML Framework
//  @ File Name : Game.cs
//  @ Date : 13/09/2016
//  @ Author : Daybson B. S. Paisante <daybson.paisante@outlook.com>
//
//

using SFML.Graphics;
using SFML.Window;
using System;
using System.Collections.Generic;

using System.Linq;
using System.Text;
using SFML.System;
using System.Threading;
using SFMLFramework;
using SFMLFramework.src.Helper;

public class Game
{
    #region Fields

    public static readonly Vector2u windowSize = new Vector2u(800, 600);
    public string windowTitle;
    public Clock clock;
    protected RenderWindow window;
    private KeyboardInput keyboard;

    private GameObject canvas;
    private UIText labelCommands;

    private bool isDebugging;
    private bool isRendering;

    private Player player;
    public Player Player { get { return player; } }

    private List<GameObject> gameObjects;
    public List<GameObject> GameObjects { get { return gameObjects; } }

    #endregion


    #region Public

    public Game(string title)
    {
        this.windowTitle = title;
        this.clock = new Clock();
        this.keyboard = new KeyboardInput(ref this.window);
        this.gameObjects = new List<GameObject>();

        this.canvas = new GameObject("Canvas");
        this.labelCommands = new UIText(this.canvas);
        this.canvas.Components.Add(labelCommands);
    }

    public void Start()
    {
        try
        {
            isDebugging = true;
            isRendering = true;
            this.window = new RenderWindow(new VideoMode(windowSize.X, windowSize.Y), windowTitle);
            this.window.SetFramerateLimit(120);
            this.window.KeyPressed += this.keyboard.ProcessKeyboardPressed;
            this.window.KeyReleased += this.keyboard.ProcessKeyboardReleased;

            this.labelCommands.Display = (v) => this.labelCommands.SetMessage(
                "A = move player esquerda\n" +
                "D = move player direita\n" +
                "Seta esqueda = move cubo1 esquerda\n" +
                "Seta direita = move cubo1 direita\n" +
                "Numpad4 = move cubo2 esquerda\n" +
                "Numpad6 = move cubo2 direita"
                );
            this.canvas.Position = new Vector2f(windowSize.X/2, 0);
            this.gameObjects.Add(this.canvas);

            this.player = GameObjectCreator.CreatePlayer(ref this.keyboard);
            this.gameObjects.Add(this.player);
            this.player.Position = V2.Right * 650;


            var elastic = GameObjectCreator.CreateElasticBrick(new Vector2f(300, 400));
            this.gameObjects.Add(elastic);
            this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Right) elastic.GetComponent<Rigidbody>().AddForce(V2.Right * 200); };
            this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Left) elastic.GetComponent<Rigidbody>().AddForce(V2.Left * 200); };

            var inelastic = GameObjectCreator.CreateInelasticBrick(new Vector2f(100, 400));
            this.gameObjects.Add(inelastic);
            this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Right) elastic.GetComponent<Rigidbody>().AddForce(V2.Right * 200); };
            this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Left) elastic.GetComponent<Rigidbody>().AddForce(V2.Left * 200); };


            var parcialInelastic = GameObjectCreator.CreatePartialInelasticBrick(new Vector2f(500, 400));
            this.gameObjects.Add(parcialInelastic);
            //this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Right) elastic.GetComponent<Rigidbody>().AddForce(V2.Right * 200); };
            //this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Left) elastic.GetComponent<Rigidbody>().AddForce(V2.Left * 200); };

            /*
            var right = GameObjectCreator.CreateElasticBrick2(new Vector2f(300, 0));
            this.gameObjects.Add(right);
            this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Numpad6) right.GetComponent<Rigidbody>().AddForce(V2.Right * 200); };
            this.window.KeyPressed += (sender, e) => { if (e.Code == Keyboard.Key.Numpad4) right.GetComponent<Rigidbody>().AddForce(V2.Left * 200); };
            */

            this.gameObjects.Add(GameObjectCreator.CreatePlatform(EDirection.Down, new Vector2f(0, windowSize.Y - 32)));
            this.gameObjects.Add(GameObjectCreator.CreatePlatform(EDirection.Right, new Vector2f(windowSize.X - 33, 29)));
            this.gameObjects.Add(GameObjectCreator.CreatePlatform(EDirection.Left, new Vector2f(0, 32)));

            this.window.KeyReleased += (sender, e) => { if (e.Code == Keyboard.Key.F) isDebugging = !isDebugging; };
            this.window.KeyReleased += (sender, e) => { if (e.Code == Keyboard.Key.R) isRendering = !isRendering; };

            this.labelCommands.Display.Invoke(V2.Zero);

            Run();
        }
        catch(Exception e)
        {
            Console.WriteLine(e.ToString());
        }
    }

    public void Update(float deltaTime)
    {
        foreach (var g in this.gameObjects)
        {
            g.Update(deltaTime);

            #region Loop de colisão
            for (var i = 0; i < this.gameObjects.Count; i++)
            {
                //evita self teste 
                if (!g.Equals(this.gameObjects[i]))
                {
                    var gRigidBody = (ICollisionable)g.GetComponent<Rigidbody>();
                    var gIndexRigidBody = (ICollisionable)gameObjects[i].GetComponent<Rigidbody>();
                    CollisionDispatcher.CollisionCheck(ref gRigidBody, ref gIndexRigidBody, deltaTime);
                }
            }
            #endregion
        }
    }

    #endregion


    #region Protected

    protected void Run()
    {
        while (this.window.IsOpen)
        {
            var timer = this.clock.Restart();

            window.DispatchEvents();
            Update(timer.AsSeconds());
            Render();
        }
    }

    protected void Render()
    {
        this.window.Clear(new Color(150, 150, 150));

        foreach (var g in this.gameObjects)
        {
            if (isRendering)
               g.GetComponent<Renderer>()?.Render(ref this.window);

            if (isDebugging)
            {
                g.GetComponent<Rigidbody>()?.ColliderBottom.Render(ref this.window);
                g.GetComponent<Rigidbody>()?.ColliderTop.Render(ref this.window);
                g.GetComponent<Rigidbody>()?.ColliderRight.Render(ref this.window);
                g.GetComponent<Rigidbody>()?.ColliderLeft.Render(ref this.window);
                g.GetComponent<UIText>()?.Render(ref this.window);
            }
        }

        this.window.Display();
    }

    #endregion
}
